### PR TITLE
updates readme to target mainly the license terms

### PR DESCRIPTION
**Pull request by kjezek**
This PR changes the readme to mainly point at the legal usage of this project

### CODE REVIEW

**Comment by b-scholz** [comment]
Can you store the interface description in docs/overview.md and link the interface description in the README?

**Comment by b-scholz** [comment]
Also, can you change "GO" to "Go"? Many thanks!

**Comment by kjezek** [comment]
> Also, can you change "GO" to "Go"? Many thanks!

done

**Comment by kjezek** [comment]
> Also, can you change "GO" to "Go"? Many thanks!

done

**Review by b-scholz — APPROVED** [review]
LGTM

**Pull request merged**
